### ISSUE TITLE
W3.js seriously?

### ISSUE THREAD

**Issue by tripulse** [hydronesiumScratch/hydronesiumScratch.github.io#12]
W3Schools is the least quality website ever made (deprecated code). I don't believe that their library is any good. See, [W3Fools](https://w3fools.com) and [this archived article][1].

[1]: https://web.archive.org/web/20110412103745/http://w3fools.com/

**Comment by Magnogen** [comment]
:'( I'll get around to completely redoing the css eventually. As you can probably tell from the fact it took so long to reply, it's not really very high on my priorities list. If you want to contribute, please do feel free to make a pull request.

**Comment by tripulse** [comment]
''
\-
