### ISSUE TITLE
More slides needed for slideshow.

### ISSUE THREAD

**Issue by Magnogen** [hydronesiumScratch/hydronesiumScratch.github.io#3]
More slides are needed in the slideshow on the homepage.

**Comment by compute-e** [comment]
A couple of public domain images I collected last year for general purpose use:

"Clouds on blue sky" | "Spirals and circles"
--- | ---
![clouds on blue sky 300x200 px](https://user-images.githubusercontent.com/13541254/30248407-2fed319a-961f-11e7-8242-dec705388bb9.png) | ![spirals and circles 300x300 px](https://user-images.githubusercontent.com/13541254/30248421-79a67242-961f-11e7-80e8-9ead06b63038.png)

You can use them in the image slideshow demonstration on your homepage.

**Comment by Magnogen** [comment]
Thanks mate. ;)
